import type { Baby } from "../../types";
import type { WeeklyStats } from "../useWeeklyStats";
import type { InsightCard } from "./insightBuilders";
import type { Tab } from "./constants";

export interface ExportParams {
  baby: Baby;
  weekRange: string;
  stats: WeeklyStats;
  insights: Record<Tab, InsightCard[]>;
  rhythmScore: number | null;
  clusterDaysCount: number;
  sleepDebtMessage: string | null;
  napArchitecture: {
    totalNaps: number;
    avgNapMin: number;
    longestStretchMin: number;
    longestStretchDay: string | null;
    totalNapHours: number;
    totalNightHours: number;
  } | null;
  hydrationMessage: string | null;
  stoolMessages: string[];
}

function formatDuration(minutes: number): string {
  const h = Math.floor(minutes / 60);
  const m = Math.round(minutes % 60);
  if (h > 0) return `${h}h ${m}m`;
  return `${m}m`;
}

export function buildWeeklySummaryExport(params: ExportParams): string {
  const {
    baby,
    weekRange,
    stats,
    rhythmScore,
    clusterDaysCount,
    sleepDebtMessage,
    napArchitecture,
    hydrationMessage,
    stoolMessages,
  } = params;

  const dob = baby.date_of_birth
    ? new Date(baby.date_of_birth)
    : null;
  const ageStr = dob
    ? (() => {
        const now = new Date();
        const months =
          (now.getFullYear() - dob.getFullYear()) * 12 +
          (now.getMonth() - dob.getMonth());
        if (months < 1) return "newborn";
        if (months < 12) return `${months} month${months === 1 ? "" : "s"} old`;
        const years = Math.floor(months / 12);
        return `${years} year${years === 1 ? "" : "s"} old`;
      })()
    : "age not set";

  const lines: string[] = [];

  lines.push(`${baby.name} — Weekly Summary ${weekRange}`);
  lines.push(`Age: ${ageStr}`);
  lines.push("");

  // Feeds
  lines.push("── FEEDS ──");
  lines.push(`Total: ${stats.totalFeeds} feeds this week`);
  lines.push(
    `Nursing: ${stats.feedInsights.nursingTotal} · Bottle: ${stats.feedInsights.bottleTotal}`,
  );
  lines.push(`Average ${stats.avgFeeds} feeds per day`);
  if (rhythmScore != null) {
    lines.push(`Rhythm score: ${rhythmScore}/100`);
  }
  if (clusterDaysCount > 0) {
    lines.push(`${clusterDaysCount} cluster feeding day(s) this week`);
  }
  lines.push("");

  // Sleep
  lines.push("── SLEEP ──");
  lines.push(`Total: ${stats.totalSleepHours}h this week`);
  if (napArchitecture) {
    lines.push(
      `Nap sleep: ${napArchitecture.totalNapHours}h · Night sleep: ${napArchitecture.totalNightHours}h`,
    );
    lines.push(
      `${napArchitecture.totalNaps} naps · avg ${formatDuration(napArchitecture.avgNapMin)} per nap`,
    );
    lines.push(
      `Longest stretch: ${formatDuration(napArchitecture.longestStretchMin)}${
        napArchitecture.longestStretchDay
          ? ` on ${napArchitecture.longestStretchDay}`
          : ""
      }`,
    );
  }
  if (sleepDebtMessage) {
    lines.push(sleepDebtMessage);
  }
  lines.push("");

  // Diapers
  lines.push("── DIAPERS ──");
  lines.push(`Total: ${stats.totalDiapers} changes this week`);
  lines.push(
    `Wet: ${stats.diaperInsights.wetTotal} · Dirty: ${stats.diaperInsights.dirtyTotal} · Both: ${stats.diaperInsights.bothTotal}`,
  );
  if (hydrationMessage) {
    lines.push(hydrationMessage);
  }
  for (const m of stoolMessages) {
    lines.push(m);
  }
  lines.push("");

  lines.push("──");
  lines.push("Generated by Cova · Share with your pediatrician as needed");

  return lines.join("\n");
}
