import { StyleSheet } from "react-native";
import { Colors } from "../../constants/theme";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.cream,
  },
  content: {
    paddingBottom: 100,
  },
  // ── Hero
  hero: {
    backgroundColor: Colors.teal,
    paddingTop: 64,
    paddingBottom: 28,
    paddingHorizontal: 24,
    borderBottomLeftRadius: 32,
    borderBottomRightRadius: 32,
  },
  heroInner: {
    flexDirection: "row",
    alignItems: "center",
    gap: 18,
  },
  avatarWrap: {
    position: "relative",
  },
  avatarRing: {
    width: 80,
    height: 80,
    borderRadius: 28,
    borderWidth: 3,
    borderColor: "rgba(255,255,255,0.35)",
    overflow: "hidden",
  },
  avatarImg: {
    width: "100%",
    height: "100%",
  },
  avatarPlaceholder: {
    flex: 1,
    backgroundColor: "rgba(255,255,255,0.12)",
    alignItems: "center",
    justifyContent: "center",
  },
  editBadge: {
    position: "absolute",
    bottom: -3,
    right: -3,
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: "white",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 4,
    elevation: 3,
  },
  heroText: {
    flex: 1,
  },
  heroName: {
    fontFamily: "Cormorant-Garamond",
    fontSize: 30,
    fontWeight: "600",
    color: "white",
    letterSpacing: -0.3,
    marginBottom: 4,
  },
  heroAge: {
    fontFamily: "DM-Sans",
    fontSize: 13,
    color: "rgba(255,255,255,0.7)",
    fontWeight: "500",
  },
  // ── Info grid
  grid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    padding: 20,
    paddingBottom: 0,
  },
  infoCard: {
    width: "47%",
    backgroundColor: Colors.sand,
    borderRadius: 18,
    padding: 14,
    borderWidth: 1,
  },
  infoValue: {
    fontFamily: "Cormorant-Garamond",
    fontSize: 17,
    fontWeight: "600",
    marginBottom: 2,
    lineHeight: 20,
  },
  infoLabel: {
    fontFamily: "DM-Sans",
    fontSize: 10,
    color: Colors.inkLight,
    textTransform: "uppercase",
    letterSpacing: 0.8,
    fontWeight: "600",
  },
  // ── Section label
  sectionLabel: {
    fontFamily: "DM-Sans",
    fontSize: 11,
    letterSpacing: 2,
    textTransform: "uppercase",
    color: Colors.inkLight,
    margin: 20,
    marginBottom: 12,
    fontWeight: "600",
  },
  // ── Stats
  statsCard: {
    backgroundColor: Colors.sand,
    borderRadius: 20,
    marginHorizontal: 20,
    padding: 4,
    marginBottom: 4,
  },
  statRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    padding: 14,
  },
  statRowBorder: {
    borderBottomWidth: 1,
    borderBottomColor: Colors.sandDark,
  },
  statIcon: {
    width: 36,
    height: 36,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  statLabel: {
    fontFamily: "DM-Sans",
    fontSize: 14,
    color: Colors.inkMid,
    flex: 1,
  },
  statValue: {
    fontFamily: "Cormorant-Garamond",
    fontSize: 22,
    fontWeight: "600",
  },
  // ── Milestones
  milestoneCard: {
    flexDirection: "row",
    gap: 14,
    alignItems: "flex-start",
    backgroundColor: Colors.cream,
    borderRadius: 18,
    marginHorizontal: 20,
    marginBottom: 10,
    padding: 14,
    borderWidth: 1,
    borderColor: Colors.gold + "22",
  },
  milestoneIcon: {
    width: 44,
    height: 44,
    borderRadius: 14,
    backgroundColor: Colors.gold + "18",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  milestoneInfo: { flex: 1 },
  milestoneTitle: {
    fontFamily: "DM-Sans",
    fontWeight: "700",
    fontSize: 14,
    color: Colors.ink,
    marginBottom: 2,
  },
  milestoneDate: {
    fontFamily: "DM-Mono",
    fontSize: 11,
    color: Colors.inkLight,
  },
  milestoneDesc: {
    fontFamily: "DM-Sans",
    fontSize: 12,
    color: Colors.inkMid,
    marginTop: 4,
    lineHeight: 17,
  },
  emptyMilestones: {
    alignItems: "center",
    paddingVertical: 32,
    marginHorizontal: 20,
  },
  emptyTitle: {
    fontFamily: "Cormorant-Garamond",
    fontSize: 20,
    color: Colors.inkLight,
    marginBottom: 4,
  },
  emptyBody: {
    fontFamily: "DM-Sans",
    fontSize: 13,
    color: Colors.inkLight,
    textAlign: "center",
  },
  addMilestoneBtn: {
    borderWidth: 1.5,
    borderColor: Colors.sandDark,
    borderStyle: "dashed",
    borderRadius: 18,
    margin: 20,
    marginTop: 10,
    padding: 16,
    alignItems: "center",
  },
  addMilestoneBtnText: {
    fontFamily: "DM-Sans",
    fontWeight: "600",
    fontSize: 14,
    color: Colors.inkLight,
  },
  // ── Edit Profile modal
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(42,32,24,0.45)",
    justifyContent: "flex-end",
  },
  modalSheet: {
    backgroundColor: Colors.cream,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    padding: 24,
    paddingBottom: 48,
    alignItems: "center",
  },
  modalHandle: {
    width: 40,
    height: 4,
    backgroundColor: Colors.sandDark,
    borderRadius: 2,
    alignSelf: "center",
    marginBottom: 20,
  },
  modalTitle: {
    fontFamily: "Cormorant-Garamond",
    fontSize: 26,
    fontWeight: "600",
    color: Colors.ink,
    marginBottom: 24,
  },
  editAvatarWrap: {
    position: "relative",
    marginBottom: 8,
  },
  editAvatarImg: {
    width: 110,
    height: 110,
    borderRadius: 36,
    borderWidth: 3,
    borderColor: Colors.teal + "30",
  },
  editAvatarPlaceholder: {
    width: 110,
    height: 110,
    borderRadius: 36,
    backgroundColor: Colors.sand,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: Colors.sandDark,
  },
  editAvatarBadge: {
    position: "absolute",
    bottom: -2,
    right: -2,
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: Colors.teal,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 3,
    borderColor: Colors.cream,
  },
  editAvatarHint: {
    fontFamily: "DM-Sans",
    fontSize: 12,
    color: Colors.inkLight,
    marginBottom: 24,
  },
  fieldLabel: {
    fontFamily: "DM-Sans",
    fontWeight: "600",
    fontSize: 13,
    color: Colors.inkMid,
    textTransform: "uppercase",
    letterSpacing: 0.8,
    alignSelf: "stretch",
    marginBottom: 6,
  },
  fieldInput: {
    backgroundColor: Colors.sand,
    borderWidth: 1.5,
    borderColor: Colors.sandDark,
    borderRadius: 14,
    padding: 14,
    fontFamily: "DM-Sans",
    fontSize: 16,
    color: Colors.ink,
    marginBottom: 24,
    alignSelf: "stretch",
  },
  saveBtn: {
    backgroundColor: Colors.teal,
    borderRadius: 18,
    padding: 17,
    alignItems: "center",
    alignSelf: "stretch",
    marginBottom: 10,
  },
  saveBtnText: {
    fontFamily: "DM-Sans",
    fontWeight: "700",
    fontSize: 16,
    color: "white",
  },
  cancelBtn: {
    borderRadius: 18,
    padding: 14,
    alignItems: "center",
    alignSelf: "stretch",
  },
  cancelBtnText: {
    fontFamily: "DM-Sans",
    fontWeight: "600",
    fontSize: 15,
    color: Colors.inkLight,
  },
  // ── Milestone modal
  milestoneModalOverlay: {
    flex: 1,
    backgroundColor: "rgba(42,32,24,0.45)",
    justifyContent: "flex-end",
  },
  milestoneModalSheet: {
    backgroundColor: Colors.cream,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    padding: 24,
    paddingBottom: 48,
  },
  milestoneModalHandle: {
    width: 40,
    height: 4,
    backgroundColor: Colors.sandDark,
    borderRadius: 2,
    alignSelf: "center",
    marginBottom: 20,
  },
  milestoneModalTitle: {
    fontFamily: "Cormorant-Garamond",
    fontSize: 24,
    fontWeight: "600",
    color: Colors.ink,
    textAlign: "center",
    marginBottom: 20,
  },
  milestoneInput: {
    backgroundColor: Colors.sand,
    borderWidth: 1.5,
    borderColor: Colors.sandDark,
    borderRadius: 14,
    padding: 14,
    fontFamily: "DM-Sans",
    fontSize: 15,
    color: Colors.ink,
    marginBottom: 12,
    marginTop: 6,
  },
  milestoneInputMultiline: {
    backgroundColor: Colors.sand,
    borderWidth: 1.5,
    borderColor: Colors.sandDark,
    borderRadius: 14,
    padding: 14,
    fontFamily: "DM-Sans",
    fontSize: 15,
    color: Colors.ink,
    marginBottom: 20,
    marginTop: 6,
    minHeight: 80,
    textAlignVertical: "top",
  },
  saveMilestoneBtn: {
    backgroundColor: Colors.gold,
    borderRadius: 18,
    padding: 17,
    alignItems: "center",
  },
  saveMilestoneBtnText: {
    fontFamily: "DM-Sans",
    fontWeight: "700",
    fontSize: 16,
    color: "white",
  },
});
