import { StyleSheet } from "react-native";
import { Colors } from "../../constants/theme";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.cream,
  },
  content: {
    padding: 24,
    paddingBottom: 100,
  },
  title: {
    fontFamily: "Cormorant-Garamond",
    fontSize: 36,
    fontWeight: "600",
    color: Colors.ink,
    marginBottom: 4,
  },
  subtitle: {
    fontFamily: "DM-Sans",
    fontSize: 14,
    color: Colors.inkLight,
    marginBottom: 28,
  },
  // ── Connected styles
  syncBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: Colors.mossPale,
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingVertical: 8,
    alignSelf: "flex-start",
    marginBottom: 20,
  },
  syncDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: Colors.moss,
  },
  syncText: {
    fontFamily: "DM-Sans",
    fontWeight: "700",
    fontSize: 12,
    color: Colors.moss,
  },
  memberCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    backgroundColor: Colors.sand,
    borderRadius: 20,
    padding: 16,
    marginBottom: 12,
  },
  avatar: {
    width: 50,
    height: 50,
    borderRadius: 16,
    backgroundColor: Colors.tealPale,
    alignItems: "center",
    justifyContent: "center",
  },
  avatarText: {
    fontFamily: "Cormorant-Garamond",
    fontSize: 20,
    fontWeight: "600",
    color: Colors.teal,
  },
  memberInfo: {
    flex: 1,
  },
  memberName: {
    fontFamily: "DM-Sans",
    fontWeight: "700",
    fontSize: 15,
    color: Colors.ink,
    marginBottom: 3,
  },
  memberRole: {
    fontFamily: "DM-Sans",
    fontSize: 12,
    color: Colors.inkLight,
  },
  onlineBadge: {
    backgroundColor: Colors.mossPale,
    borderRadius: 20,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  onlineText: {
    fontFamily: "DM-Sans",
    fontWeight: "700",
    fontSize: 11,
    color: Colors.moss,
  },
  statsRow: {
    flexDirection: "row",
    gap: 10,
    marginTop: 8,
  },
  statCard: {
    flex: 1,
    backgroundColor: Colors.sand,
    borderRadius: 16,
    padding: 16,
    alignItems: "center",
  },
  statValue: {
    fontFamily: "Cormorant-Garamond",
    fontSize: 26,
    fontWeight: "600",
    color: Colors.teal,
    marginBottom: 4,
  },
  statLabel: {
    fontFamily: "DM-Sans",
    fontSize: 10,
    color: Colors.inkLight,
    textTransform: "uppercase",
    letterSpacing: 0.5,
    fontWeight: "600",
  },
  // ── Invite styles
  hero: {
    backgroundColor: Colors.tealPale,
    borderRadius: 24,
    padding: 24,
    marginBottom: 20,
  },
  heroTitle: {
    fontFamily: "Cormorant-Garamond",
    fontSize: 26,
    fontWeight: "600",
    color: Colors.teal,
    marginBottom: 8,
  },
  heroBody: {
    fontFamily: "DM-Sans",
    fontSize: 14,
    color: Colors.inkMid,
    lineHeight: 21,
  },
  codeCard: {
    backgroundColor: Colors.sand,
    borderRadius: 20,
    padding: 20,
    alignItems: "center",
    marginBottom: 16,
  },
  codeCardLabel: {
    fontFamily: "DM-Sans",
    fontSize: 10,
    letterSpacing: 2,
    color: Colors.inkLight,
    marginBottom: 8,
    textTransform: "uppercase",
    fontWeight: "600",
  },
  codeCardValue: {
    fontFamily: "DM-Mono",
    fontSize: 30,
    fontWeight: "500",
    color: Colors.teal,
    letterSpacing: 4,
    marginBottom: 6,
  },
  codeCardSub: {
    fontFamily: "DM-Sans",
    fontSize: 11,
    color: Colors.inkLight,
    fontStyle: "italic",
  },
  primaryBtn: {
    backgroundColor: Colors.teal,
    borderRadius: 18,
    padding: 17,
    alignItems: "center",
    marginBottom: 12,
    shadowColor: Colors.teal,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 6,
  },
  primaryBtnText: {
    fontFamily: "DM-Sans",
    fontWeight: "700",
    fontSize: 16,
    color: "white",
  },
  secondaryBtn: {
    alignItems: "center",
    paddingVertical: 12,
    marginBottom: 8,
  },
  secondaryBtnText: {
    fontFamily: "DM-Sans",
    fontSize: 14,
    fontWeight: "600",
    color: Colors.teal,
  },
  emailSection: {
    marginTop: 4,
    marginBottom: 16,
  },
  fieldLabel: {
    fontFamily: "DM-Sans",
    fontSize: 12,
    fontWeight: "600",
    color: Colors.inkLight,
    letterSpacing: 1,
    textTransform: "uppercase",
    marginBottom: 8,
  },
  emailInput: {
    backgroundColor: Colors.sand,
    borderWidth: 1.5,
    borderColor: Colors.sandDark,
    borderRadius: 16,
    padding: 15,
    fontFamily: "DM-Sans",
    fontSize: 15,
    color: Colors.ink,
    marginBottom: 12,
  },
  benefitRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: Colors.sandDark,
  },
  benefitText: {
    fontFamily: "DM-Sans",
    fontSize: 13,
    color: Colors.inkMid,
    flex: 1,
    lineHeight: 18,
  },
});
