import { StyleSheet } from "react-native";
import { Colors } from "../../constants/theme";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.cream },
  content: { padding: 20, paddingTop: 60, paddingBottom: 100 },

  headerRow: {
    flexDirection: "row",
    alignItems: "flex-end",
    marginBottom: 24,
  },
  title: {
    fontFamily: "Cormorant-Garamond",
    fontSize: 32,
    fontWeight: "600",
    color: Colors.ink,
    letterSpacing: -0.3,
    lineHeight: 36,
  },
  subtitle: {
    fontFamily: "DM-Sans",
    fontSize: 13,
    color: Colors.inkLight,
    marginTop: 4,
  },

  tabRow: {
    flexDirection: "row",
    gap: 6,
    marginBottom: 20,
    backgroundColor: Colors.sand,
    borderRadius: 18,
    padding: 4,
  },
  tab: {
    flex: 1,
    borderRadius: 14,
    paddingVertical: 10,
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "center",
    gap: 6,
  },
  tabText: {
    fontFamily: "DM-Sans",
    fontWeight: "600",
    fontSize: 13,
    color: Colors.inkLight,
  },

  chartCard: {
    backgroundColor: Colors.sand,
    borderRadius: 22,
    padding: 18,
    marginBottom: 24,
  },
  statStrip: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 24,
  },
  statItem: {
    flex: 1,
    alignItems: "center",
    minHeight: 52,
  },
  statValue: {
    fontFamily: "Cormorant-Garamond",
    fontSize: 28,
    fontWeight: "700",
    lineHeight: 30,
  },
  statSuffix: {
    fontFamily: "DM-Sans",
    fontSize: 13,
    fontWeight: "600",
    marginLeft: 1,
  },
  statLabel: {
    fontFamily: "DM-Sans",
    fontSize: 10,
    color: Colors.inkLight,
    textTransform: "uppercase",
    letterSpacing: 0.8,
    fontWeight: "600",
    marginTop: 3,
  },
  statDivider: {
    width: 1,
    height: 28,
    backgroundColor: Colors.sandDark,
  },

  chartArea: {
    position: "relative",
    height: 170,
    paddingTop: 20,
  },
  gridLine: {
    position: "absolute",
    left: 0,
    right: 0,
    height: 1,
    backgroundColor: Colors.sandDark + "80",
  },
  referenceLine: {
    position: "absolute",
    left: 0,
    right: 0,
    flexDirection: "row",
    alignItems: "center",
    height: 18,
    marginBottom: -9,
  },
  referenceLineTrack: {
    flex: 1,
    height: 2,
    backgroundColor: Colors.teal + "99",
  },
  referenceLineLabel: {
    fontFamily: "DM-Sans",
    fontSize: 9,
    color: Colors.teal,
    fontWeight: "600",
    marginRight: 6,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  avgLine: {
    flex: 1,
    height: 0,
    borderStyle: "dashed",
    borderTopWidth: 1,
    borderTopColor: Colors.inkLight + "99",
  },
  avgLineLabel: {
    fontFamily: "DM-Sans",
    fontSize: 9,
    color: Colors.inkLight,
    fontWeight: "600",
    marginRight: 6,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  trendArrowWrap: {
    position: "absolute",
    top: 0,
    right: 0,
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  trendArrowText: {
    fontFamily: "DM-Sans",
    fontSize: 11,
    fontWeight: "700",
  },
  peakIndicator: {
    position: "absolute",
    top: -18,
    alignSelf: "center",
    minWidth: 28,
    height: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  peakIndicatorText: {
    fontFamily: "DM-Sans",
    fontSize: 8,
    fontWeight: "700",
    color: Colors.teal,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  zeroFeedPlaceholder: {
    width: "70%",
    minHeight: 12,
    borderRadius: 8,
    backgroundColor: Colors.sandDark + "30",
    alignItems: "center",
    justifyContent: "center",
  },
  zeroFeedPlaceholderText: {
    fontFamily: "DM-Sans",
    fontSize: 10,
    color: Colors.inkLight,
    fontWeight: "500",
  },
  barsRow: {
    flexDirection: "row",
    gap: 8,
    alignItems: "flex-end",
    flex: 1,
    marginLeft: 44,
  },
  barWrap: {
    flex: 1,
    alignItems: "center",
    height: "100%",
    borderRadius: 12,
    paddingVertical: 4,
  },
  barWrapSelected: {
    backgroundColor: Colors.sandDark + "40",
  },
  barTrack: {
    flex: 1,
    width: "100%",
    justifyContent: "flex-end",
    alignItems: "center",
  },
  bar: {
    width: "70%",
    minHeight: 4,
  },
  barValue: {
    fontFamily: "DM-Sans",
    fontSize: 10,
    fontWeight: "600",
    marginBottom: 6,
  },
  dayLabel: {
    fontFamily: "DM-Sans",
    fontSize: 11,
    color: Colors.inkLight,
    marginTop: 10,
    fontWeight: "500",
  },

  barDetail: {
    marginTop: 14,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: Colors.sandDark + "50",
  },
  barDetailMain: {
    fontFamily: "DM-Sans",
    fontSize: 13,
    color: Colors.ink,
    lineHeight: 20,
  },
  barDetailDay: {
    fontWeight: "700",
  },
  barDetailValue: {
    fontWeight: "500",
    color: Colors.inkMid,
  },
  barDetailSub: {
    fontFamily: "DM-Sans",
    fontSize: 12,
    marginTop: 4,
    fontWeight: "500",
  },
  barDetailHint: {
    fontFamily: "DM-Sans",
    fontSize: 11,
    color: Colors.inkLight,
    marginTop: 18,
    textAlign: "center",
  },

  legendRow: {
    flexDirection: "row",
    justifyContent: "center",
    gap: 20,
    marginTop: 12,
  },
  legendItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  legendDot: {
    width: 10,
    height: 10,
    borderRadius: 3,
  },
  legendText: {
    fontFamily: "DM-Sans",
    fontSize: 11,
    color: Colors.inkLight,
    fontWeight: "500",
  },
  wetDirtyShiftNote: {
    fontFamily: "DM-Sans",
    fontSize: 10,
    color: Colors.inkLight,
    marginTop: 8,
    fontStyle: "italic",
    textAlign: "center",
  },
  sectionLabel: {
    fontFamily: "DM-Sans",
    fontSize: 11,
    letterSpacing: 2,
    textTransform: "uppercase",
    color: Colors.inkLight,
    marginBottom: 12,
    fontWeight: "600",
  },
  insightCard: {
    padding: 14,
    backgroundColor: Colors.cream,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: Colors.sandDark + "60",
    borderLeftWidth: 3,
    marginBottom: 10,
  },
  insightHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: 6,
  },
  insightIcon: {
    width: 32,
    height: 32,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  insightTitle: {
    fontFamily: "DM-Sans",
    fontSize: 14,
    fontWeight: "700",
    color: Colors.ink,
  },
  insightText: {
    fontFamily: "DM-Sans",
    fontSize: 13,
    color: Colors.inkMid,
    lineHeight: 19,
    paddingLeft: 42,
  },
  balanceBarTrack: {
    flexDirection: "row",
    height: 6,
    borderRadius: 3,
    overflow: "hidden",
    marginTop: 10,
    marginLeft: 42,
    backgroundColor: Colors.sandDark,
  },
  balanceBarLeft: {
    minWidth: 2,
  },
  balanceBarRight: {
    minWidth: 2,
  },
  exportBtn: {
    borderRadius: 16,
    padding: 16,
    alignItems: "center",
    marginTop: 8,
  },
  exportBtnText: {
    fontFamily: "DM-Sans",
    fontWeight: "700",
    fontSize: 14,
  },
});
